import type { CollectionConfig } from '@/types/app'

export const ATO_KM_RATE = 0.88
export const DEFAULT_TAX_RATE = 0.25

export const configs: Record<string, CollectionConfig> = {
  customers: {
    collection: 'customers', label: 'Customers', singular: 'Customer', path: '/customers',
    description: 'People and businesses you work for.',
    listFields: ['name', 'phone', 'email', 'suburb'],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'phone', label: 'Phone', type: 'tel' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'address', label: 'Address' },
      { name: 'suburb', label: 'Suburb' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  jobs: {
    collection: 'jobs', label: 'Jobs', singular: 'Job', path: '/jobs',
    listFields: ['jobNumber', 'title', 'customerName', 'status', 'quotedAmount'],
    fields: [
      { name: 'jobNumber', label: 'Job number', placeholder: 'auto: J-1001' },
      { name: 'title', label: 'Job title', required: true },
      { name: 'customerName', label: 'Customer' },
      { name: 'address', label: 'Address/suburb' },
      { name: 'status', label: 'Status', type: 'select', options: ['ACTIVE', 'COMPLETED', 'CANCELLED'], defaultValue: 'ACTIVE' },
      { name: 'quotedAmount', label: 'Quoted amount', type: 'number' },
      { name: 'workspaceId', label: 'Business stream', type: 'select', options: ['my-business'], defaultValue: 'my-business' },
      { name: 'actualHours', label: 'Actual hours', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  quotes: {
    collection: 'quotes', label: 'Quotes', singular: 'Quote', path: '/quotes',
    listFields: ['quoteNumber', 'customerName', 'status', 'total'],
    fields: [
      { name: 'quoteNumber', label: 'Quote number', placeholder: 'Q-0001' },
      { name: 'customerName', label: 'Customer' },
      { name: 'title', label: 'Title' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'SENT', 'ACCEPTED', 'DECLINED'], defaultValue: 'DRAFT' },
      { name: 'total', label: 'Total', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  invoices: {
    collection: 'invoices', label: 'Invoices', singular: 'Invoice', path: '/invoices',
    listFields: ['invoiceNumber', 'customerName', 'status', 'total'],
    fields: [
      { name: 'invoiceNumber', label: 'Invoice number', placeholder: 'INV-0001' },
      { name: 'customerName', label: 'Customer' },
      { name: 'jobTitle', label: 'Job title' },
      { name: 'invoiceDate', label: 'Invoice date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'SENT', 'PART_PAID', 'PAID', 'VOID'], defaultValue: 'DRAFT' },
      { name: 'total', label: 'Invoice total', type: 'number', required: true },
      { name: 'amountPaid', label: 'Amount paid', type: 'number', defaultValue: 0 },
      { name: 'balanceOwing', label: 'Balance owing', type: 'number', defaultValue: 0 },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  expenses: {
    collection: 'expenses', label: 'Expenses', singular: 'Expense', path: '/finance',
    listFields: ['description', 'category', 'date', 'amount'],
    fields: [
      { name: 'description', label: 'Description', required: true },
      { name: 'workspaceId', label: 'Business stream', type: 'select', options: ['my-business'], defaultValue: 'my-business' },
      { name: 'linkedJobNumber', label: 'Linked job number' },
      { name: 'jobTitle', label: 'Linked job title' },
      { name: 'category', label: 'Category', type: 'select', options: ['Materials', 'Tools', 'Fuel', 'Phone', 'Insurance', 'Vehicle', 'Software', 'Other'], defaultValue: 'Other' },
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'gstIncluded', label: 'GST included', type: 'checkbox' },
      { name: 'jobTitle', label: 'Linked job' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  materials: {
    collection: 'materials', label: 'Materials', singular: 'Material', path: '/materials',
    listFields: ['name', 'supplier', 'quantity', 'totalCost'],
    fields: [
      { name: 'name', label: 'Material/item', required: true },
      { name: 'supplier', label: 'Supplier' },
      { name: 'quantity', label: 'Quantity', type: 'number', defaultValue: 1 },
      { name: 'unitCost', label: 'Unit cost', type: 'number' },
      { name: 'totalCost', label: 'Total cost', type: 'number' },
      { name: 'markupPercent', label: 'Markup %', type: 'number' },
      { name: 'workspaceId', label: 'Business stream', type: 'select', options: ['my-business'], defaultValue: 'my-business' },
      { name: 'linkedJobNumber', label: 'Linked job number' },
      { name: 'jobTitle', label: 'Linked job' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  travelLogs: {
    collection: 'travelLogs', label: 'Travel / KMs', singular: 'Travel log', path: '/travel',
    listFields: ['date', 'fromLocation', 'toLocation', 'distanceKm'],
    fields: [
      { name: 'date', label: 'Date', type: 'date' },
      { name: 'fromLocation', label: 'From' },
      { name: 'toLocation', label: 'To' },
      { name: 'distanceKm', label: 'Distance KM', type: 'number', required: true },
      { name: 'workspaceId', label: 'Business stream', type: 'select', options: ['my-business'], defaultValue: 'my-business' },
      { name: 'linkedJobNumber', label: 'Linked job number' },
      { name: 'parkingCost', label: 'Parking', type: 'number' },
      { name: 'tollsCost', label: 'Tolls', type: 'number' },
      { name: 'jobTitle', label: 'Linked job' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  leads: {
    collection: 'leads', label: 'Leads', singular: 'Lead', path: '/leads',
    listFields: ['customerName', 'jobType', 'status', 'source'],
    fields: [
      { name: 'customerName', label: 'Customer name' },
      { name: 'phone', label: 'Phone', type: 'tel' },
      { name: 'source', label: 'Source', type: 'select', options: ['Facebook', 'Messenger', 'Phone', 'Referral', 'Website', 'Other'], defaultValue: 'Other' },
      { name: 'jobType', label: 'Job type' },
      { name: 'status', label: 'Status', type: 'select', options: ['NEW', 'AWAITING_DETAILS', 'QUOTE_BOOKED', 'QUOTE_SENT', 'WON', 'LOST'], defaultValue: 'NEW' },
      { name: 'address', label: 'Address/suburb' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  appointments: {
    collection: 'appointments', label: 'Appointments', singular: 'Appointment', path: '/appointments',
    listFields: ['title', 'customerName', 'startTime', 'status'],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'customerName', label: 'Customer' },
      { name: 'startTime', label: 'Start time', type: 'datetime-local' },
      { name: 'endTime', label: 'End time', type: 'datetime-local' },
      { name: 'status', label: 'Status', type: 'select', options: ['REQUESTED', 'BOOKED', 'COMPLETED', 'CANCELLED'], defaultValue: 'BOOKED' },
      { name: 'address', label: 'Address/suburb' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
}
